export const KITCHEN_DEFAULTS = {
  PRIORITY: 'NORMAL',
  DEFAULT_PREPARATION_TIME_MINUTES: 15,
  MAX_TICKET_ITEMS: 100,
} as const;

export const KITCHEN_LIMITS = {
  MAX_QUERY_LIMIT: 100,
  DEFAULT_QUERY_LIMIT: 20,
} as const;
