export const ORDER_DEFAULTS = {
  STATUS: 'DRAFT',
  TYPE: 'DINE_IN',
  PAYMENT_STATUS: 'UNPAID',
  FULFILLMENT_STATUS: 'UNFULFILLED',
  DEFAULT_TAX_RATE: 0.05, // 5% GST/VAT default
  DEFAULT_SERVICE_FEE_RATE: 0,
} as const;

export const ORDER_LIMITS = {
  MAX_ITEMS_PER_ORDER: 100,
  MAX_QUANTITY_PER_ITEM: 99,
  DEFAULT_QUERY_LIMIT: 20,
  MAX_QUERY_LIMIT: 100,
} as const;
