export enum StaffStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  TERMINATED = 'TERMINATED',
}

export enum StaffType {
  FULL_TIME = 'FULL_TIME',
  PART_TIME = 'PART_TIME',
  CONTRACT = 'CONTRACT',
  TEMPORARY = 'TEMPORARY',
}

export enum StaffDepartment {
  MANAGEMENT = 'MANAGEMENT',
  FRONT_OF_HOUSE = 'FRONT_OF_HOUSE',
  KITCHEN = 'KITCHEN',
  DELIVERY = 'DELIVERY',
  INVENTORY = 'INVENTORY',
  CLEANING = 'CLEANING',
  SECURITY = 'SECURITY',
  OTHER = 'OTHER',
}