export const STAFF_DEFAULTS = {
  STATUS: 'ACTIVE',
  TYPE: 'FULL_TIME',
  DEPARTMENT: 'FRONT_OF_HOUSE',
} as const;

export const STAFF_LIMITS = {
  MAX_DISPLAY_NAME_LENGTH: 150,
  MAX_EMPLOYEE_CODE_LENGTH: 50,
  MAX_POSITION_LENGTH: 100,
} as const;