export enum DeliveryStatus {
    PENDING = 'PENDING',
    ASSIGNMENT_PENDING = 'ASSIGNMENT_PENDING',
    ASSIGNED = 'ASSIGNED',
    ACCEPTED = 'ACCEPTED',
    READY_FOR_PICKUP = 'READY_FOR_PICKUP',
    PICKED_UP = 'PICKED_UP',
    OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
    ARRIVED = 'ARRIVED',
    DELIVERED = 'DELIVERED',
    FAILED = 'FAILED',
    CANCELLED = 'CANCELLED',
}

export enum DeliveryPartnerType {
    RESTAURANT_STAFF = 'RESTAURANT_STAFF',
    THIRD_PARTY = 'THIRD_PARTY',
    EXTERNAL_DRIVER = 'EXTERNAL_DRIVER',
}

export enum DeliveryFailureReason {
  CUSTOMER_UNAVAILABLE = 'CUSTOMER_UNAVAILABLE',
    WRONG_ADDRESS = 'WRONG_ADDRESS',
    CUSTOMER_CANCELLED = 'CUSTOMER_CANCELLED',
    VEHICLE_ISSUE = 'VEHICLE_ISSUE',
    RESTAURANT_DELAY = 'RESTAURANT_DELAY',
    WEATHER = 'WEATHER',
    OTHER = 'OTHER',
}

export enum DeliveryAttemptStatus {
    STARTED = 'STARTED',
    FAILED = 'FAILED',
    SUCCESSFUL = 'SUCCESSFUL',
}
