export const MENU_DEFAULTS = {
  STATUS: 'DRAFT',
  ITEM_STATUS: 'AVAILABLE',
  PRICING_TYPE: 'FIXED',
  SPICE_LEVEL: 'NONE',
} as const;

export const MENU_LIMITS = {
  MAX_NAME_LENGTH: 150,
  MAX_DESCRIPTION_LENGTH: 1000,
  MAX_CATEGORY_NAME_LENGTH: 100,
  MAX_PRICE: 1_000_000,
} as const;
