export enum BranchStatus {
    ACTIVE = 'ACTIVE',
    INACTIVE = 'INACTIVE',
    TEMPORARILY_CLOSED = 'TEMPORARILY_CLOSED',
    PERMANENTLY_CLOSED = 'PERMANENTLY_CLOSED'
}

export enum BranchType {
  MAIN = 'MAIN',
  STANDARD = 'STANDARD',
  EXPRESS = 'EXPRESS',
  CLOUD_KITCHEN = 'CLOUD_KITCHEN',
  FOOD_COURT = 'FOOD_COURT',
}

